apiVersion: "kubedirector.hpe.com/v1beta1"
kind: "KubeDirectorCluster"
metadata:
  name: "orion-gpu-slice"
spec:
  app: orion-gpu-slice
  roles:
  - id: controller
    resources:
      requests:
        memory: "4Gi"
        cpu: "2"
        nvidia.com/gpu-thread: "1"        
      limits:
        memory: "4Gi"
        cpu: "2"
        nvidia.com/gpu-thread: "1"